### ISSUE TITLE
Download folder

### ISSUE THREAD

**Issue by Mozart1221** [obskyr/khinsider#41]
where i can change fix path of download files, right in the script?

**Comment by vtdiep** [comment]
A bit of a long post, but I hope it answers your question. The first option didn't occur to me at first, but it's the most straightforward.

- Run khinsider.py from where you want the soundtrack folders to be created.
 You want to download into ~\a\music
khinsider.py is at ~\a\b\khinsider
**cd into ~\a\music**
Then run `python ~\a\b\khinsider\khinsider.py desired-ost-here optional-custom-folder-name-here`
The files should then be downloaded into ~\a\music\optional-custom-folder-name-here

- Run khinsider.py from wherever khinsider.py is located
  Let's say you're at **\a\b\khinsider**, which is where khinsider.py is located.
  - Locations at/inside khinsider.py location
  
  
    If you want to download files into \a\b\khinsider\katamari_ost, then
 ` khinsider.py katamari-forever "katamari_ost" `

    If you want to download files into \a\b\khinsider\music\katamari_ost
  ` khinsider.py katamari-forever "music\katamari_ost" `


  - Download path locations outside of khinsider.py location:

    If you want to download the files to a location **outside** of wherever the script is located,
(ie you want to download into \a\b\music\katamari_ost, which is outside of \a\b\khinsider), you can use the absolute path
` khinsider.py katamari-forever "\a\b\music\katamari_ost" `
or relative path
` khinsider.py katamari-forever "..\music\katamari_ost" `

   - **Note that using ~ by itself may not work as intended**
` khinsider.py katamari-forever "~\katamari_ost" `
will create \a\b\khinsider\\\~\katamari_ost
and yes, that is a folder called "~"

      interestingly, ` khinsider.py katamari-forever "~\..\katamari_ost" `
will create \a\b\khinsider\katamari_ost, which is equivalent to \a\b\khinsider\\\~\\\..\katamari_ost

- An actual hard-code modification
If you want to keep how folders are automatically named after the soundtrack, but just want to move where those folders are located, replace getcwd() in https://github.com/obskyr/khinsider/blob/870b74f3970953d8af92928150e4ae99a2785bbf/khinsider.py#L312
with the desired location, but don't use a ~ based filepath.

@obskyr 
This is really regarding option 2, which might be irrelevant since option 1 exists, but since I've already written it down:
 I'm not sure if you want to make any changes, given the existence of a solution, but if you want to allow use of ~ as a path and not a directory name, os.path.expanduser(path) will do the job.
But then that might mean that you can't manually set your downloads into a folder called ~,
though I'm not sure why one would want to do that.

I suppose the current download-directory argument could be split into output-folder-name and output-folder-location... but I'm not sure if potential for confusion/complexity would increase...

**Comment by Mozart1221** [comment]
thanks bro, explained a lot┌(・。・)┘
